name: Sync from upstream

on:
  schedule:
    - cron: '*/1 * * * *'  
  workflow_dispatch:        
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream https://github.com/LostInLogic/artwebsiteproject.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Sync upstream changes"
          git push origin main
