name: Sync from upstream test

on:
  schedule:
    - cron: '*/2 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "⏰ Cron job ran at $(date)"
