name: Merge upstream branches

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Merge upstream
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
          git pull --unshallow
      
          git remote add upstream https://github.com/LostInLogic/artwebsiteproject.git
          git fetch upstream
      
          git merge --no-edit upstream/main
          git push origin main


permissions:
  contents: write
